# Generated by Django 5.1.3 on 2024-12-05 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_client_email_remove_client_name_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.task'),
            preserve_default=False,
        ),
    ]
