# Generated by Django 5.1.3 on 2024-12-05 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_task_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name_user', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='user_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
