version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=postgres
      - DB_USER=testeag
      - DB_PASSWORD=testeag
      - DB_HOST=db
      - DB_PORT=5432
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testeag
      POSTGRES_PASSWORD: testeag
      POSTGRES_DB: testeag 
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
